src/Entity/Series.php
<?php

namespace App\Entity;

use App\Repository\SeriesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SeriesRepository::class)]
class Series
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $nbr_question = null;

    #[ORM\Column(length: 255)]
    private ?string $descriptions = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNbrQuestion(): ?string
    {
        return $this->nbr_question;
    }

    public function setNbrQuestion(string $nbr_question): static
    {
        $this->nbr_question = $nbr_question;

        return $this;
    }

    public function getDescriptions(): ?string
    {
        return $this->descriptions;
    }

    public function setDescriptions(string $descriptions): static
    {
        $this->descriptions = $descriptions;

        return $this;
    }
    public function __toString()
    {
        $result = $this->titre. $this->nbr_question . $this->descriptions;
        return $result;
    }
}

src/Form/SeriesType.php
<?php

namespace App\Form;

use App\Entity\Series;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SeriesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('nbr_question')
            ->add('descriptions')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Series::class,
        ]);
    }
}

src/Controller/SeriesController.php
<?php

namespace App\Controller;

use App\Entity\Series;
use App\Form\SeriesType;
use App\Repository\SeriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/series')]
class SeriesController extends AbstractController
{
    #[Route('/', name: 'app_series_index', methods: ['GET'])]
    public function index(SeriesRepository $seriesRepository): Response
    {
        return $this->render('series/index.html.twig', [
            'series' => $seriesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_series_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SeriesRepository $seriesRepository): Response
    {
        $series = new Series();
        $form = $this->createForm(SeriesType::class, $series);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $seriesRepository->save($series, true);

            return $this->redirectToRoute('app_series_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('series/new.html.twig', [
            'series' => $series,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_series_show', methods: ['GET'])]
    public function show(Series $series): Response
    {
        return $this->render('series/show.html.twig', [
            'series' => $series,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_series_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Series $series, SeriesRepository $seriesRepository): Response
    {
        $form = $this->createForm(SeriesType::class, $series);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $seriesRepository->save($series, true);

            return $this->redirectToRoute('app_series_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('series/edit.html.twig', [
            'series' => $series,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_series_delete', methods: ['POST'])]
    public function delete(Request $request, Series $series, SeriesRepository $seriesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$series->getId(), $request->request->get('_token'))) {
            $seriesRepository->remove($series, true);
        }

        return $this->redirectToRoute('app_series_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/series/_delete_form.html.twig
<form method="post" action="{{ path('app_series_delete', {'id': series.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ series.id) }}">
    <button class="btn">Delete</button>
</form>

templates/series/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/series/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Series{% endblock %}

{% block body %}
    <h1>Edit Series</h1>

    {{ include('series/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_series_index') }}">back to list</a>

    {{ include('series/_delete_form.html.twig') }}
{% endblock %}

templates/series/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Series index{% endblock %}

{% block body %}
    <h1>Series index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Nbr_question</th>
                <th>Descriptions</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for series in series %}
            <tr>
                <td>{{ series.id }}</td>
                <td>{{ series.titre }}</td>
                <td>{{ series.nbrQuestion }}</td>
                <td>{{ series.descriptions }}</td>
                <td>
                    <a href="{{ path('app_series_show', {'id': series.id}) }}">show</a>
                    <a href="{{ path('app_series_edit', {'id': series.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_series_new') }}">Create new</a>
{% endblock %}

templates/series/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Series{% endblock %}

{% block body %}
    <h1>Create new Series</h1>

    {{ include('series/_form.html.twig') }}

    <a href="{{ path('app_series_index') }}">back to list</a>
{% endblock %}

templates/series/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Series{% endblock %}

{% block body %}
    <h1>Series</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ series.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ series.titre }}</td>
            </tr>
            <tr>
                <th>Nbr_question</th>
                <td>{{ series.nbrQuestion }}</td>
            </tr>
            <tr>
                <th>Descriptions</th>
                <td>{{ series.descriptions }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_series_index') }}">back to list</a>

    <a href="{{ path('app_series_edit', {'id': series.id}) }}">edit</a>

    {{ include('series/_delete_form.html.twig') }}
{% endblock %}