src/Entity/Reponses.php
<?php

namespace App\Entity;

use App\Repository\ReponsesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReponsesRepository::class)]
class Reponses
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $correct_reponse = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $detail_reponse = null;

    #[ORM\Column(length: 255)]
    private ?string $reponse_candidat = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Candidat $candidat = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCorrectReponse(): ?string
    {
        return $this->correct_reponse;
    }

    public function setCorrectReponse(string $correct_reponse): static
    {
        $this->correct_reponse = $correct_reponse;

        return $this;
    }

    public function getDetailReponse(): ?string
    {
        return $this->detail_reponse;
    }

    public function setDetailReponse(string $detail_reponse): static
    {
        $this->detail_reponse = $detail_reponse;

        return $this;
    }

    public function getReponseCandidat(): ?string
    {
        return $this->reponse_candidat;
    }

    public function setReponseCandidat(string $reponse_candidat): static
    {
        $this->reponse_candidat = $reponse_candidat;

        return $this;
    }

    public function getCandidat(): ?Candidat
    {
        return $this->candidat;
    }

    public function setCandidat(?Candidat $candidat): static
    {
        $this->candidat = $candidat;

        return $this;
    }
    public function __toString()
    {
        $result=$this->correct_reponse;
        return $result;
    }
}

src/Form/ReponsesType.php
<?php

namespace App\Form;

use App\Entity\Reponses;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReponsesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('correct_reponse')
            ->add('detail_reponse')
            ->add('reponse_candidat')
            ->add('candidat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reponses::class,
        ]);
    }
}

src/Controller/ReponsesController.php
<?php

namespace App\Controller;

use App\Entity\Reponses;
use App\Form\ReponsesType;
use App\Repository\ReponsesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reponses')]
class ReponsesController extends AbstractController
{
    #[Route('/', name: 'app_reponses_index', methods: ['GET'])]
    public function index(ReponsesRepository $reponsesRepository): Response
    {
        return $this->render('reponses/index.html.twig', [
            'reponses' => $reponsesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_reponses_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReponsesRepository $reponsesRepository): Response
    {
        $reponse = new Reponses();
        $form = $this->createForm(ReponsesType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponsesRepository->save($reponse, true);

            return $this->redirectToRoute('app_reponses_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reponses/new.html.twig', [
            'reponse' => $reponse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reponses_show', methods: ['GET'])]
    public function show(Reponses $reponse): Response
    {
        return $this->render('reponses/show.html.twig', [
            'reponse' => $reponse,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reponses_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reponses $reponse, ReponsesRepository $reponsesRepository): Response
    {
        $form = $this->createForm(ReponsesType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reponsesRepository->save($reponse, true);

            return $this->redirectToRoute('app_reponses_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reponses/edit.html.twig', [
            'reponse' => $reponse,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reponses_delete', methods: ['POST'])]
    public function delete(Request $request, Reponses $reponse, ReponsesRepository $reponsesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reponse->getId(), $request->request->get('_token'))) {
            $reponsesRepository->remove($reponse, true);
        }

        return $this->redirectToRoute('app_reponses_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reponses/_delete_form.html.twig
<form method="post" action="{{ path('app_reponses_delete', {'id': reponse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reponse.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reponses/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reponses/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reponses{% endblock %}

{% block body %}
    <h1>Edit Reponses</h1>

    {{ include('reponses/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reponses_index') }}">back to list</a>

    {{ include('reponses/_delete_form.html.twig') }}
{% endblock %}

templates/reponses/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponses index{% endblock %}

{% block body %}
    <h1>Reponses index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Correct_reponse</th>
                <th>Detail_reponse</th>
                <th>Reponse_candidat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reponse in reponses %}
            <tr>
                <td>{{ reponse.id }}</td>
                <td>{{ reponse.correctReponse }}</td>
                <td>{{ reponse.detailReponse }}</td>
                <td>{{ reponse.reponseCandidat }}</td>
                <td>
                    <a href="{{ path('app_reponses_show', {'id': reponse.id}) }}">show</a>
                    <a href="{{ path('app_reponses_edit', {'id': reponse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_reponses_new') }}">Create new</a>
{% endblock %}

templates/reponses/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reponses{% endblock %}

{% block body %}
    <h1>Create new Reponses</h1>

    {{ include('reponses/_form.html.twig') }}

    <a href="{{ path('app_reponses_index') }}">back to list</a>
{% endblock %}

templates/reponses/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reponses{% endblock %}

{% block body %}
    <h1>Reponses</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reponse.id }}</td>
            </tr>
            <tr>
                <th>Correct_reponse</th>
                <td>{{ reponse.correctReponse }}</td>
            </tr>
            <tr>
                <th>Detail_reponse</th>
                <td>{{ reponse.detailReponse }}</td>
            </tr>
            <tr>
                <th>Reponse_candidat</th>
                <td>{{ reponse.reponseCandidat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reponses_index') }}">back to list</a>

    <a href="{{ path('app_reponses_edit', {'id': reponse.id}) }}">edit</a>

    {{ include('reponses/_delete_form.html.twig') }}
{% endblock %}